### PR TITLE
Add support for server rendering

### PR DESCRIPTION
**Pull request by mrwade**
`document` is not defined on the server and therefore blows up when attempting to render server-side.

### CODE REVIEW

**Comment by caseywebdev** [comment]
LGTM, thanks Kevin!

**Comment by caseywebdev** [comment]
Released in `0.8.2`

**Comment by mrwade** [comment]
🎉  Thanks!

**Comment by jpowell** [comment]
Oh, you guys!

**Comment by tylerlee** [comment]
i was trying to figure out how to deny this

**Comment by clifton** [comment]
go away @tylerlee

**Comment by tfausak** [comment]
> i was trying to figure out how to deny this

turborude

**Comment by caseywebdev** [comment]
> > i was trying to figure out how to deny this

> turborude

cantfix wontfix

**Pull request merged**
